src/app/app_modules/stocks/urls.py
from flask import Blueprint
from .views import CreateStockView , StockDataTableView

stock_bp = Blueprint('stock_bp', __name__)

stock_bp.add_url_rule('/create-stock', view_func=CreateStockView.as_view('create_stock'))
stock_bp.add_url_rule('/api/stocks', view_func=StockDataTableView.as_view('stock_data_table'))

src/app/app_modules/users/urls.py
from flask import Blueprint
from .views import CreateUserView, DeleteUser, UserDataTableView, UserUpdateView, UserListView , GetSalesRepresentativeAjax,EmployeeDataTableView
user_bp = Blueprint('user_bp', __name__)

user_bp.add_url_rule('/users', view_func=UserListView.as_view('user_list'))
user_bp.add_url_rule('/user/<int:user_id>/delete/', view_func=DeleteUser.as_view('delete_user'))
user_bp.add_url_rule('/create-user', view_func=CreateUserView.as_view('create_user'))
user_bp.add_url_rule('/<int:id>/update-user', view_func=UserUpdateView.as_view('update_user'))
user_bp.add_url_rule('/api/users', view_func=UserDataTableView.as_view('user_data_table'))
user_bp.add_url_rule('/api/employees', view_func=EmployeeDataTableView.as_view('employee_data_table'))
user_bp.add_url_rule('/api/get-sales-representatives', view_func=GetSalesRepresentativeAjax.as_view('get_sales_representative_ajax'))

src/app/app_modules/stocks/models.py
from app import db
from sqlalchemy.sql import func
from ..base.models import BaseModel
from ..company.models import Company
from ..products.models import Product , ProductCase
from ..vendors.models import Vendor
from ..warehouse.models import Warehouse
from ..zones.models import Zone
from ..users.models import User

class Stock(BaseModel):

    __tablename__ = 'stock'

    total_stock     = db.Column(db.Integer, default=0)

    company_id      = db.Column(db.Integer, db.ForeignKey(Company.id), nullable=True)
    company         = db.relationship(Company, backref=db.backref('company_stock', lazy=True))
    vendor_id       = db.Column(db.Integer, db.ForeignKey(Vendor.id), nullable=True)
    vendor          = db.relationship(Vendor, backref=db.backref('vendor', lazy=True))
    warehouse_id    = db.Column(db.Integer, db.ForeignKey(Warehouse.id), nullable=True)
    warehouse       = db.relationship(Warehouse, backref=db.backref('stock_warehouse', lazy=True))
    product_id      = db.Column(db.Integer, db.ForeignKey(Product.id), nullable=False)
    product         = db.relationship(Product, backref=db.backref('products', lazy=True))

    @property
    def get_locked_stock(self):
        total_locked_stock = db.session.query(func.sum(StockHistory.locked_quantity)).filter_by(product_id=self.product_id).scalar()
        return total_locked_stock or 0
    
    @property
    def get_load_stock(self):
        total_load_stock = db.session.query(func.sum(StockHistory.load_quantity)).filter_by(product_id=self.product_id).scalar()
        return total_load_stock or 0

    def __repr__(self):
        return f'<Stock {self.product.name}>'

class StockHistory(BaseModel):

    __tablename__ = 'stock_history'

    IN = "in"
    OUT = "out"

    TYPE_CHOICES = [
        (IN, 'In'),
        (OUT, 'Out'),
    ]

    CREATED = "created"
    UPDATED = "updated"

    STATUS_CHOICES = [
        (CREATED, CREATED),
        (UPDATED, UPDATED),
    ]

    no_of_case              = db.Column(db.Integer, default=0)
    manufacture_date        = db.Column(db.Date, nullable=True)
    expiry_date             = db.Column(db.Date, nullable=True)
    stock                   = db.Column(db.Integer, default=0)
    affected_stock          = db.Column(db.Integer, default=0)
    before_stock            = db.Column(db.Integer, default=0)
    per_piece_price         = db.Column(db.Integer, default=0)
    total_amount            = db.Column(db.Numeric(10, 2), default=0)
    type                    = db.Column(db.String(50), default=IN)
    locked_quantity         = db.Column(db.Integer, default=0, nullable=True)
    load_quantity           = db.Column(db.Integer, default=0, nullable=True)
    remark                  = db.Column(db.Text, nullable=True)
    status                  = db.Column(db.String(100), default=CREATED)
    is_deleted              = db.Column(db.Boolean, default=False)
    removed_at              = db.Column(db.Date, nullable=True)

    product_id              = db.Column(db.Integer, db.ForeignKey(Product.id), nullable=False)
    product                 = db.relationship(Product, backref=db.backref('product_stock', lazy=True))
    product_case_id         = db.Column(db.Integer, db.ForeignKey(ProductCase.id), nullable=True)
    product_case            = db.relationship(ProductCase, backref=db.backref('product_stock_set', lazy=True))
    modified_by_id          = db.Column(db.Integer, db.ForeignKey(User.id), nullable=True)
    modified_by             = db.relationship(User, backref=db.backref('stock_set', lazy=True))
    warehouse_id            = db.Column(db.Integer, db.ForeignKey(Warehouse.id), nullable=True)
    warehouse               = db.relationship(Warehouse, backref=db.backref('warehouse_stock_history', lazy=True))
    zone_id                 = db.Column(db.Integer, db.ForeignKey(Zone.id), nullable=False)
    zone                    = db.relationship(Zone, backref=db.backref('zone_stock_history', lazy=True))
    vendor_id               = db.Column(db.Integer, db.ForeignKey(Vendor.id), nullable=True)
    vendor                  = db.relationship(Vendor, backref=db.backref('stock_set', lazy=True))

    @property
    def get_zone_wise_current_stock(self):
        stock_agg = db.session.query(
            func.sum(StockHistory.affected_stock).label('total_affected_stock'),
            func.sum(StockHistory.locked_quantity).label('total_locked_quantity'),
            func.sum(StockHistory.load_quantity).label('total_load_quantity')
        ).filter(
            StockHistory.zone_id == self.zone_id,
            StockHistory.product_id == self.product_id,
            StockHistory.status == StockHistory.CREATED,
            StockHistory.affected_stock > StockHistory.locked_quantity,
            StockHistory.is_deleted == False
        ).one_or_none()

        total_affected_stock = stock_agg.total_affected_stock or 0
        total_locked_quantity = stock_agg.total_locked_quantity or 0
        total_load_quantity = stock_agg.total_load_quantity or 0

        return total_affected_stock - (total_locked_quantity + total_load_quantity) if total_affected_stock >= (total_locked_quantity + total_load_quantity) else 0

    def __repr__(self):
        return f'<StockHistory {self.product.name}>'

# class ManageStockHistory(BaseModel):

#     __tablename__ = 'manage_stock_history'

#     IN = "in"
#     OUT = "out"

#     TYPE_CHOICES = [
#         (IN, 'In'),
#         (OUT, 'Out'),
#     ]

#     affected_stock  = db.Column(db.Integer, default=0)
#     current_stock   = db.Column(db.Integer, default=0)
#     per_piece_price = db.Column(db.Integer, default=0)
#     total_amount    = db.Column(db.Numeric(10, 2), default=0)
#     stock_type      = db.Column(db.String(50), default=IN)

#     stock_id        = db.Column(db.Integer, db.ForeignKey(StockHistory.id), nullable=True)
#     stock           = db.relationship(StockHistory, backref=db.backref('manage_stock_history_set', lazy=True))
#     load_product_id = db.Column(db.Integer, db.ForeignKey('load_order_products.id'), nullable=True)
#     load_product    = db.relationship('LoadOrderProducts', backref=db.backref('manage_stock_history_set', lazy=True))
#     product_id      = db.Column(db.Integer, db.ForeignKey('product.id'), nullable=False)
#     product         = db.relationship('Product', backref=db.backref('product_manage_stock_history', lazy=True))
#     product_case_id = db.Column(db.Integer, db.ForeignKey('product_case.id'), nullable=True)
#     product_case    = db.relationship('ProductCase', backref=db.backref('product_manage_stock_history', lazy=True))
#     modified_by_id  = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
#     modified_by     = db.relationship('User', backref=db.backref('manage_stock_history_set', lazy=True))
#     warehouse_id    = db.Column(db.Integer, db.ForeignKey('warehouse.id'), nullable=True)
#     warehouse       = db.relationship('Warehouse', backref=db.backref('warehouse_manage_stock_history', lazy=True))
#     zone_id         = db.Column(db.Integer, db.ForeignKey('zone.id'), nullable=False)
#     zone            = db.relationship('Zone', backref=db.backref('zone_manage_stock_history', lazy=True))
#     vendor_id       = db.Column(db.Integer, db.ForeignKey('vendor.id'), nullable=True)
#     vendor          = db.relationship('Vendor', backref=db.backref('manage_stock_history', lazy=True))

#     def __repr__(self):
#         return f'<ManageStockHistory {self.product.name}>'

# class LockedProductStock(BaseModel):

#     __tablename__ = 'locked_product_stock'

#     locked_quantity  = db.Column(db.Integer, default=0, nullable=True)
#     is_deleted       = db.Column(db.Boolean, default=False)

#     order_id         = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
#     order            = db.relationship('Order', backref=db.backref('locked_product_stock_set', lazy=True))
#     order_product_id = db.Column(db.Integer, db.ForeignKey('order_product.id'), nullable=False)
#     order_product    = db.relationship('OrderProduct', backref=db.backref('locked_product_stock_set', lazy=True))
#     stock_id         = db.Column(db.Integer, db.ForeignKey('stock_history.id'), nullable=False)
#     stock            = db.relationship('StockHistory', backref=db.backref('locked_product_stock_set', lazy=True))

# class MissingProductStock(BaseModel):

#     __tablename__ = 'missing_product_stock'

#     missing_quantity = db.Column(db.Integer, default=0, nullable=True)
#     order_id         = db.Column(db.Integer, db.ForeignKey('order.id'), nullable=False)
#     order            = db.relationship('Order', backref=db.backref('missing_product_stock_set', lazy=True))
#     order_product_id = db.Column(db.Integer, db.ForeignKey('order_product.id'), nullable=False)
#     order_product    = db.relationship('OrderProduct', backref=db.backref('missing_product_stock_set', lazy=True))

#     def __repr__(self):
#         return f'<MissingProductStock {self.order_product}>'

src/app/app_modules/zones/models.py
from flask import url_for
from app import db
from app.app_modules.base.models import BaseModel


class Zone(BaseModel):

    __tablename__ = 'Zone'

    ACTIVE = "active"
    INACTIVE = "inactive"
    
    STATUS_CHOICES = (
        (ACTIVE, ACTIVE),
        (INACTIVE, INACTIVE),
    )
    
    name            = db.Column(db.String(100), nullable=False)
    status          = db.Column(db.String(100), nullable=True)
    warehouse_id    = db.Column(db.Integer, db.ForeignKey('Warehouse.id'), nullable=True)
    warehouse       = db.relationship('Warehouse', backref=db.backref('warehouse_zone', lazy=True))

    def __repr__(self):
        return self.name
    
    @property
    def get_status_display(self):
        return dict(self.STATUS_CHOICES).get(self.status, '')

src/app/app_modules/stocks/views.py
from app import db
from flask.views import MethodView
from flask import Response, jsonify, redirect, render_template, request, url_for
from sqlalchemy import or_

from app.app_modules.base.base_views import BaseCreateView, BaseListView
from app.app_modules.products.models import Product
from app.app_modules.warehouse.models import Warehouse
from app.helper.utils import update_history_obj
from .models import Stock, StockHistory
from .forms import StockCreateForm

class CreateStockView(BaseCreateView):

    model = StockHistory
    form_class = StockCreateForm
    template_name = "stock/stock_form.html"

    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs['company_id'] = request.args.get('company_id')
        kwargs['product_id'] = request.args.get('product_id')
        return kwargs
    
    def get_context_data(self, form=None, **kwargs):
        ctx = super().get_context_data(form, **kwargs)
        product_id = request.args.get('product_id')
        ctx['total_stock'] = 0
        ctx['company_id'] = request.args.get('company_id')
        ctx['product_id'] = product_id
        return ctx


    def post(self, **kwargs):
        company_id = request.form.get('company_id')
        product_id = request.form.get('product_id')
        form = self.form_class(request.form, company_id=int(company_id),product_id=int(product_id))
        try:
            if form.validate_on_submit():
                new_stock = self.model(
                    product_id = request.form.get('product_id'),
                    warehouse_id = form.warehouse_id.data,
                    zone_id = form.zone_id.data,
                    vendor_id = form.vendor_id.data,
                    product_case_id = form.product_case_id.data,
                    no_of_case = form.no_of_case.data,
                    affected_stock = form.affected_stock.data,
                    per_piece_price = form.per_piece_price.data,
                    total_amount = form.total_amount.data,
                    manufacture_date = form.manufacture_date.data,
                    expiry_date = form.expiry_date.data,
                )
                modified_by_id = form.modified_by_id.data
                if modified_by_id > 0:
                    new_stock.modified_by_id = modified_by_id
                
                stock_obj = Stock.query.filter_by(product_id=product_id,company_id = company_id).first()

                if not stock_obj:
                    stock_obj = Stock(product_id=product_id,company_id = company_id)
                    new_stock.before_stock = stock_obj.total_stock
                    stock_obj.total_stock = int(form.affected_stock.data)
                else:
                    new_stock.before_stock = stock_obj.total_stock
                    stock_obj.total_stock += int(form.affected_stock.data)

                db.session.add(new_stock)
                db.session.commit()

                stock_obj.warehouse_id = form.warehouse_id.data
                stock_obj.vendor_id = form.vendor_id.data
                db.session.add(stock_obj)
                db.session.commit()

                update_history_obj(new_stock.id)

                return jsonify({'status': 'success', 'message': 'Stock created successfully!'}), 200
            else:
                return jsonify({'status': 'error', 'errors': form.errors}), 400

        except Exception as e:
            db.session.rollback()
            return jsonify({'status': 'error', 'message': 'An error occurred while processing the form.'}), 500


class StockDataTableView(MethodView):

    def _get_actions(self, obj):
        detail_url = "#"
        
        return (
            f'<div><span class="log_history_model mx-1" data-product_id="{obj.product.id}" data-id="{ obj.id }"'
            + f' title="History" data-bs-target="#myModal" data-bs-toggle="modal"><i class="fa fa-history text-success" style="cursor:pointer;"></i></span>'
            + f'<a href="{detail_url}" title="Detail"><i class="fa fa-eye font-medium-3"></i></a></div>'
        )

    def get(self):
        from sqlalchemy import cast, String

        product_id = request.args.get('product_id')
        company_id = request.args.get('company_id')
        search = request.args.get('search[value]')

        query = Stock.query.order_by(-Stock.id)
        if product_id:
            query = query.filter(Stock.product_id == product_id)
        if company_id:
            query = query.filter(Stock.company_id == company_id)
        if search:
            query = query.filter(
                or_(
                    Stock.product.has(Product.name.ilike(f'%{search}%')),
                    Stock.warehouse.has(Warehouse.name.ilike(f'%{search}%')),
                    Stock.product.has(Product.code.ilike(f'%{search}%'))
                )
            )
            

        start = int(request.args.get('start', 0))
        length = int(request.args.get('length', 10))
        stocks = query.offset(start).limit(length).all()

        data = []
        for index, stock in enumerate(stocks,start=1):
            data.append({
                "id": index,
                "product_code": stock.product.code,
                "product": stock.product.name,
                "available_stock": 0,
                "locked_quantity": 0,
                "actions": self._get_actions(stock)
            })

        return jsonify({
            "draw": int(request.args.get('draw', 1)),
            "recordsTotal": Stock.query.count(),
            "recordsFiltered": query.count(),
            "data": data
        })

src/app/templates/stock/get_product_case_stock.html
<div class="mt-2">

    <div id="case_stock_info-{{ stock.id }}" style="position: fixed; z-index: 10; display:none; ">
        <div class="card p-3" style="border:2px solid lightblue; width: 100%; height: auto; border-radius: 5px;">
            <div class="my-1"><h5>Product Case Stock</h5></div>
            <div class="px-2">
                <table class="table table-bordered" id="month">
                    <thead>
                        <tr class="text-center">
                            <th>Weight</th>
                            <th>Quantity</th>
                            <th class="text-center" style="width:50px">CMV</th>
                            <th>Stock</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for case in stock.product.product_case.all %}
                        <tr class="text-center">
                            <td>{{case.weight}}</td>
                            <td>{{case.quantity}}</td>
                            <td>{{case.cubic_meter_volume}}</td>
                            <td>{{case.get_total_stock}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr class="text-center">
                            <td colspan="3" class="text-end"><b>Total</b></td>
                            <td><b>{{ stock.product.get_total_available_stock }}</b></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>

    <div>
       <button class="btn text-white py-1" style="background-color: #0981b5;" onmouseover="hoverdiv(event,'case_stock_info-{{ stock.id }}')" onmouseout="hoverdiv(event,'case_stock_info-{{ stock.id }}')">
           <b>Total Stock : {{ stock.product.get_total_available_stock }}</b>
       </button>
    </div>
</div>

src/app/templates/stock/stock_create.html
<div class="row my-3">
  <div class="col-sm-5">
    <div class="row">
      <div class="col-md-4">
        <label for="id_company_list">Select Company<span class="asteriskField">*</span> : </label>
      </div>
      <div class="col-md-8">
        <select class="form-control select2" name="company_list" id="id_company_list">
          <option value="" selected>---------</option>
          {% for company in company_list %}
          <option value="{{ company.id }}">{{ company.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
  </div>

  <div class="col-md-7">
    <div class="row">
      <div class="col-md-3">
        <label for="id_product_list">Select Product<span class="asteriskField">*</span> : </label>
      </div>
      <div class="col-md-6">
        <select name="product_list" class="select2" id="id_product_list"></select>
      </div>
      <div class="col-md-2">
        <button type="button" 
              hx-get="{{ url_for('stock_bp.create_stock') }}" 
              hx-target="#sidebar_form" 
              hx-swap="innerHTML" 
              onclick="stock_add()"
              class="btn btn-primary"
              id="add_stock_button">
          Add Stock
      </button>
      </div>
    </div>
  </div>
</div>

{% include "stock/stock_list.html" %}

{% block script %}
<script src="{{ url_for('static', filename='assets/js/htmx_1.9.4.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.1.0/js/select2.min.js"></script>
<script>

  $(document).ready(function() {
    $("#id_company_list").select2({
      placeholder: "Search by company name",
      allowClear: true,    
      tags: true,          
    });

    $("#id_product_list").select2({
      placeholder: "Search by product code, name, and barcode",
      allowClear: true,    
      tags: true,          
    });
      var get_products_url = "{{ url_for('product_bp.get_products_ajax') }}";
      $(document).on('change', '#id_company_list', function(e) {
        var companyId = $(this).val();
        $.ajax({
          url: get_products_url, 
          type: 'GET',
          data: {
              company_id: companyId 
          },
          success: function(response) {
                console.log(response); 
                
                var selectProductDropdown = $('#id_product_list'); 
                selectProductDropdown.empty();
                
                if (response.products && Array.isArray(response.products)) {
                    response.products.forEach(product => {
                        var newOption = $('<option></option>').val(product.id).text(product.text);
                        selectProductDropdown.append(newOption);
                    });
                } else {
                    console.error('Invalid response format:', response);
                }
            },
          error: function(xhr, status, error) {
              console.error('AJAX request failed:', status, error);
          }
      });
      });
  });

  function stock_add(){
    let id = $("#id_product_list").val();
    if(id){
      $('#sidebar_form').toggleClass('sidebar-open');
    }
    else{
      $.toast({
        text: "Select the product to add stock !!!",
        position: 'bottom-right',
        stack: false,
        icon: 'warning',
      });
    }
  }
</script>
<script>
  function updateHtmxAttributes() {
      var productId = $("#id_product_list").val();
      var companyId = $("#id_company_list").val();
      var button = document.getElementById('add_stock_button');
      button.setAttribute('hx-vals', JSON.stringify({
          product_id: productId,
          company_id: companyId
      }));
  }
  document.getElementById('add_stock_button').addEventListener('click', updateHtmxAttributes);
</script>

{% endblock script %}

src/app/templates/stock/stock_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="my-4">
                        <h4 class="card-title align-self-center">Stock Details</h4>
                    </div>
                    <div class="d-flex">
                        <div class="mr-4">
                            <span class="font-weight-bold">Product name : </span>
                            {{ object.product.name }}
                        </div>
                        <div class="mx-4">
                            <span class="font-weight-bold">Product code : </span>
                            {{ object.product.code }}
                        </div>
                        <div class="mx-4">
                            <span class="font-weight-bold">Total stock : </span>
                            {{ object.total_stock }}
                        </div>
                        <div class="mx-4">
                            <span class="font-weight-bold">Total locked stock : </span>
                            <span class="text-danger">{{ object.get_locked_stock }}</span>
                        </div>
                        <div class="mx-4">
                            <span class="font-weight-bold">Total saleable stock : </span>
                            <span class="text-success">{{ total_saleable_stock }}</span>
                        </div>
                    </div>
                    <div class="my-4">
                        <h2 class="nav-tab-wrapper">
                            <span data-id="#tab-0" class="btn btn-outline-primary ml-sm-0 tab-2 nav-tab-active">All</span>
                            {% for zone in zone_list %}
                                <span data-id="#tab-{{ forloop.counter }}" class="btn btn-outline-primary ml-sm-0 tab-2 nav-tab">{{ zone.0 }}</span>
                            {% endfor %}
                        </h2>
                    </div>
                    <section id="tab-0" class="tab-content active">
                        <table class="table border-top-0 table-striped table-bordered border-bottom" style="width: 100%;" id="product_case_stock_table">
                            <thead>
                                <tr>
                                    <th class="text-center">Sr No.</th>
                                    <th class="text-center">Weight</th>
                                    <th class="text-center">Cubic Meter Volume (CMV)</th>
                                    <th class="text-center">Quantity</th>
                                    <th class="text-center">Available Stock</th>
                                    <th class="text-center">Last Added Stock Date</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                            </tbody>
                        </table>
                    </section>
                    {% for zone in zone_list %}
                        <section id="tab-{{ forloop.counter }}" class="tab-content">
                            <table class="table border-top-0 table-striped table-bordered border-bottom" style="width: 100%;" id="stock_detail_zone_{{ forloop.counter }}">
                                <thead>
                                    <tr>
                                        <th class="text-center">Sr No.</th>
                                        <th class="text-center">Date</th>
                                        <th class="text-center">Modifed By</th>
                                        <th class="text-center">Manufacture Date</th>
                                        <th class="text-center">Expiry Date</th>
                                        <th class="text-center">Case Size</th>
                                        <th class="text-center">Piece Per Price (₹)</th>
                                        <th class="text-center">Piece Per Price ($)</th>
                                        <th class="text-center" style="width:100px">Affected Stock</th>
                                        <th class="text-center">Locked Stock</th>
                                        <th class="text-center">Total Amount (₹)</th>
                                        <th class="text-center">IN / OUT</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody class="text-center">
                                </tbody>
                            </table>
                        </section>
                        {% empty %}
                        <p>No stock available </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row row-sm">
    <div class="col-lg-12">
        <a href="{% url 'products:product_list' %}" class="btn btn-dark"><span class="bi bi-arrow-return-left"></span> Back</a>
    </div>
</div>

{% endblock %}


{% block form %}
    {% include 'stock/stock_update.html' %}
{% endblock form %}


{% block script %}
<script src="{% static 'assets/webapp/tabbing.js' %}"></script>
<script src="{% static 'assets/js/htmx_1.9.4.min.js' %}"></script>

<script>
    $('#product_case_stock_table').DataTable({
        columnDefs: [{
            orderable: true,
            targets: -1
        },
        {
            orderable: false,
            targets: [-1],
        },
        ],
        processing: true,
        serverSide: true,
        ajax: {
            url: '{% url "manage_stock:product_case_stock_ajax" %}',
            type: 'get',
            data: {
                'product_id':{{ object.product.id|safe }},
            }
        },
        columns: [
            { data: 'id', name: 'id' },
            { data: 'weight', name: 'weight' },
            { data: 'cubic_meter_volume', name: 'cubic_meter_volume' },
            { data: 'quantity', name: 'quantity' },
            { data: 'stock', name: 'stock' },
            { data: 'last_stock_date', name: 'last_stock_date' },
        ],
        rowCallback: function(nRow, aData, iDisplayIndex) {
            var oSettings = this.fnSettings();
            $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
            return nRow;
        },
    });
    {% for zone in zone_list %}
        $('#stock_detail_zone_{{ forloop.counter }}').DataTable({
            columnDefs: [{
                orderable: true,
                targets: -1
            },
            {
                orderable: false,
                targets: [-1],
            },
            ],
            processing: true,
            serverSide: true,
            ajax: {
                url: '{% url "manage_stock:stock_detail_products_ajax" %}',
                type: 'get',
                data: {
                    'zone_id':{{ zone.1|safe }},
                    'product_id':{{ object.product.id|safe }},
                }
            },
            order: [0 , "desc"],
            columns: [
                { data: 'id', name: 'id' },
                { data: 'created_at', name: 'created_at' },
                { data: 'modified_by', name: 'modified_by' },
                { data: 'stock__manufacture_date', name: 'stock__manufacture_date' },
                { data: 'stock__expiry_date', name: 'stock__expiry_date' },
                { data: 'product_case', name: 'product_case' },
                { data: 'per_piece_price', name: 'per_piece_price' },
                { data: 'stock__per_piece_price_dollar', name: 'stock__per_piece_price_dollar' },
                { data: 'affected_stock', name: 'affected_stock' },
                { data: 'stock__locked_quantity', name: 'stock__locked_quantity' },
                { data: 'total_amount', name: 'total_amount' },
                { data: 'stock_type', name: 'stock_type' },
                { data: 'actions', name: 'actions' },
            ],
            rowCallback: function(nRow, aData, iDisplayIndex) {
                var oSettings = this.fnSettings();
                $("td:first", nRow).html(oSettings._iDisplayStart + iDisplayIndex + 1);
                return nRow;
            },
        });
    {% endfor %}

    $(document).ready(function(){
        var is_stock_updated = localStorage.getItem("is_stock_updated");
        if(is_stock_updated == "true"){
            $.toast({
                text: localStorage.getItem("message"),
                position: 'bottom-right',
                stack: false,
                icon: localStorage.getItem("level"),
            });
            localStorage.setItem("is_stock_updated", "false");
        }
    })
</script>

<script>
    $(document).on('click', '.update_stock' , function (e) {
        let url = $(this).data("url");

        htmx.ajax('GET', url, {
            target:'#sidebar_form',
            swap:'innerHTML',
        }).then(() => {
            $('#sidebar_form').toggleClass('sidebar-open');
        });
    });
</script>
{% endblock script %}